### ISSUE TITLE
Using tabs as site navbar no longer works

### ISSUE THREAD

**Issue by msprev** [imperavi/kube#100]
I've been using Kube tabs to make my navigation bar to other pages on my site. This has started to choke Kube: my collapse widgets now no longer work. This seems to be because tabs expect a corresponding div, which contains the body of the tab. There is no such div here as the tab has no content: the tab title is just being used a link to another page. 

Is there any workaround for this so I can keep using tabs to create my navbar?

Here is what I have that now no longer works:

```
<nav class="tabs" data-component="tabs">
    <ul>
        <li class="active"> <a href="http://localhost:1313/homepage-public/">Home</a> </li>
        <li> <a href="http://localhost:1313/homepage-public/x/">X</a> </li>
        <li> <a href="http://localhost:1313/homepage-public/y/">Y</a> </li>
    </ul>
</nav>
```

**Comment by swalter88** [comment]
You could just remove the `data-component="tabs"` part.  Or am i missing something?

**Comment by msprev** [comment]
Thanks, but this would mean that Kube's tab elements wouldn't be used. But I've found a workaround not using tabs in the meantime. I guess that Kube tabs are not meant for building navbars to other webpages. They are only for tabbing between within-page content. So I'm closing the issue.
