### ISSUE TITLE
Asked a permission to use kube  in a open source  theme for hugo

### ISSUE THREAD

**Issue by jeblister** [imperavi/kube#101]
Hi,
I  just finished a <a href="https://gohugo.io">hugo</a> template using `kube` and i designed this template  with the same original philosophy of your framework.

Can I publish this theme based on Kube for open source  MIT License ? I asked that because in my demo i use your assets (images, css code, font) from your documentation website.

PS. The kube framework is listed in my demo page and as a credits on the readme file.
Thanks you.

**Comment by imperavi** [comment]
Hi, 
Yes, of course. You don't need our permissions because Kube has MIT license and allows you to modify and use the framework as you wish.
