### ISSUE TITLE
add to npm

### ISSUE THREAD

**Issue by smussell** [imperavi/kube#30]
I am wondering if it is possible to add this framework to npm, or at least add a package.json file to github, so it can be easily installed via npm.  I am trying to simplify my projects by loading both client and server dependencies from npm and kube is the only package I use that is not available on both.  There are other css libraries doing this, for example https://www.npmjs.com/package/purecss.  Thanks.

**Comment by twobit** [comment]
+1. Any update?

**Comment by seqs** [comment]
+1

**Comment by glasswork** [comment]
+1

**Comment by langri-sha** [comment]
+1, thanks!

**Comment by Omnomios** [comment]
I got impatient and made my own, if Imperavi ever want to make an official one then I'll cross that bridge when I come to it.

https://www.npmjs.com/package/imperavi-kube
