### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by JJ** [imperavi/kube#34]
I can't seem to make icons work here https://github.com/JJ/splash-volunteer/blob/master/public/index.html

I have tested several containers, but no way. They simply don't show up.

**Comment by wdebusschere** [comment]
JJ, You need to load Fontawesome..

http://fortawesome.github.io/Font-Awesome/get-started/
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

**Comment by JJ** [comment]
OK. Thanks!
