### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by yegor256** [imperavi/kube#40]
Is it hosted somewhere on CDN?

**Comment by cihadturhan** [comment]
Did you check cdnjs?

https://cdnjs.com/libraries/kube

**Comment by yegor256** [comment]
@cihadturhan yes, it has an old version 3.0.2

**Comment by anshooarora** [comment]
+ 1

Please update the files on cdnjs.  It is still having the old version 3.0.2.

**Comment by makenskiy** [comment]
Hi guys! How find JS lib for kube 3.0.2 versions?

**Comment by badcat** [comment]
@makenskiy I've not seen links to them directly anymore, but here's where all the old HTML files call the scripts...

http://k1.imperavi.com/js/navigation-fixed.js
http://k1.imperavi.com/js/message.js
http://k1.imperavi.com/js/tabs.js
http://k1.imperavi.com/js/buttons.js
http://k1.imperavi.com/js/accordion.js
http://k1.imperavi.com/js/filterbox.js
http://k1.imperavi.com/js/tooltip.js
http://k1.imperavi.com/js/dropdown.js
http://k1.imperavi.com/js/livesearch.js
http://k1.imperavi.com/js/upload.js
http://k1.imperavi.com/js/progress.js
http://k1.imperavi.com/js/modal.js
http://k1.imperavi.com/js/check-all.js
http://k1.imperavi.com/js/autocomplete.js
http://k1.imperavi.com/js/infinite-scroll.js
http://k1.imperavi.com/js/navigation-toggle.js
http://k1.imperavi.com/js/textfit.js

**Comment by makenskiy** [comment]
Thank you!
