### ISSUE TITLE
"file" input type is not supported?

### ISSUE THREAD

**Issue by yegor256** [imperavi/kube#41]
Looks like your CSS doesn't understand `file` type of `<input>` form element. No formatting is applied to it. Or I'm doing something wrong?

```html
<form method="post" action="#" enctype="multipart/form-data" class="forms forms-inline">
  <input name="file" type="file"/>
  <button class="btn btn-blue" type="submit">Upload</button>
  <div class="forms-desc">Maximum file size is 10mb</div>
</form>
```

**Comment by cihadturhan** [comment]
File input is rendered by the default style sheet from the browser. Unfortunately you can't change it neither in kube nor in bootstrap etc. There are some tricks to change the appearance like set visibility hidden and apply a foreground image but none of them changes the actual appearance.
