### ISSUE TITLE
Why do not customize `select` element

### ISSUE THREAD

**Issue by jgrossi** [imperavi/kube#42]
Hi! Why don't you customize de `select` element inside the form helper?

It will be nice to have horizontal form elements following the same style.

Thanks and congrats for the job ;-)

**Comment by JessNielsen** [comment]
they have plans for it. 
If you look at the stencils theres a styled select there.
http://imperavi.com/kube/stencils/

**Comment by jgrossi** [comment]
Thanks for the feedback @JessNielsen ;-)
