### ISSUE TITLE
Documentation for v.4 removed

### ISSUE THREAD

**Issue by darren-edm** [imperavi/kube#51]
Hi,

I'm currently working on a project that is utilising the js components from v.4. As you have removed all documentation for these components from your website. It is all well that you have deprecated components from the library, but you have to continue to support previous versions for existing users. Can you add this up as either a subsection or as a download ASAP so I can continue working with the framework?

Regards,
Darren

**Comment by imperavi** [comment]
Hi,
Here is old documentation: http://k1.imperavi.com

**Comment by darren-edm** [comment]
Thanks for the swift response, thats perfect.

Regards,
Darren

**Comment by insperedia** [comment]
Documentation disappeared
