### ISSUE TITLE
kube 5 documentation has no javascript....

### ISSUE THREAD

**Issue by somenxavier** [imperavi/kube#52]
Hi,

In old kube 4 documentation, you have javascript components like [tabs](http://k1.imperavi.com/index.php?m=js-tabs) and fontsawesome examples...

Now in k5, there are no such components. Does it mean that they are removed? 

Thanks,

**Comment by badcat** [comment]
They mentioned DEPRECATED Extensive JS - I guess that's now ALL JS
https://imperavi.com/kube/log/
In the aftermath, I guess we lose more features here without JS, but at least we're now working with Flexbox :)

**Comment by somenxavier** [comment]
But is it planning to be included in the milestone?

**Comment by webarthur** [comment]
Where is the kube 5 github? ^^

**Comment by aschle** [comment]
What about navbars in kube. There used to be one right?

**Comment by pdxbmw** [comment]
+1 for navbars.

**Comment by lukeholder** [comment]
https://imperavi.com/kube/faq/

> What? Where’s the Nav Bar and other navigation?

> With over 15 years of web development experience under the belt, we can assure you that Nav Bars and all other sorts of navigational elements are always faster and easier to build for a project from scratch than to modify, customize and rebuild an existing solution.

> Each and every project has its unique navigational needs and often requires more of a custom approach. Vast experience shows that writing code for navigation from ground up is less time-consuming and more efficient, than tweaking and creating the navigation based on a boilerplate solution.
