### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by antonreshetov** [imperavi/kube#55]
Where can I find old documentation for the v5.0?

**Comment by Superanton** [comment]
They took the old documentation down. There is a point in the [FAQ](http://imperavi.com/kube/faq/): "Old versions of Kube are critically outdated, and we strongly encourage you to stop using them as soon as you can. We do not offer old versions for download, and we do not provide old documentation."

But I found the old documentation in the web archive if you need it urgently: [http://web.archive.org/web/20160318171700/https://imperavi.com/kube/css/](http://web.archive.org/web/20160318171700/https://imperavi.com/kube/css/)
