### ISSUE TITLE
Kube 6 - Toggleme with Dropdown closing issue

### ISSUE THREAD

**Issue by gregpmx** [imperavi/kube#61]
Using Dropdown inside nav with Toggleme works only one time after page is loaded. Trying to open Dropdown again instantly closes nav.

http://i.imgur.com/aOQ7MnC.gifv

Chrome 51.0.2704.103 m, Opera 38.0.2220.41
Windows 10

**Comment by marlosirapuan** [comment]
change `overflow: auto;` to `overflow: hidden;` on .dropdown class (**_dropdown.scss**)
