### ISSUE TITLE
Mixin needed for base font

### ISSUE THREAD

**Issue by bgarrant** [imperavi/kube#64]
It would be great to have a mixin to set the base font-family for entire site.  Only way I found to do it currently is by adding the variable to the theming.scss file:

`$font-family: 'Roboto', sans-serif;
$heading-font-family: $font-family;`

**Comment by bgarrant** [comment]
If I am using the https://imperavi.com/kube/docs/quick-start/#h-development option, how can I setup a base font for the site?  Looking to change a variable but I can;t see where to do it?

Looking for something like:
`$font-family: 'Roboto', sans-serif;`

**Comment by bgarrant** [comment]
The only way I found to override the default fonts without a mixin was to use this.  Is there another way?

`* { font-family: 'Roboto', sans-serif !important; }`

**Comment by invasoria** [comment]
Check out the "**_variables.scss**" file. You can change "**$font-family**" and "**$heading-font-family**"  to your desired fonts. You can also override these variables in your "**_theming.scss**" file.

**Comment by bgarrant** [comment]
That is what I am doing, but if someone just wants to include the dist/css/Kube.css file and Kube.scss method (without compiling) there is no mixin or any other way I can see to change the base font.
