### ISSUE TITLE
Readme links go to wrong page

### ISSUE THREAD

**Issue by ncksllvn** [imperavi/kube#74]
The links at the bottom of the readme for getting started are linking to `docs/started/`, when it should be `docs/quick-start/`. The links currently go to a broken page with an error at the top.

```
Notice: Undefined property: model::$name in /home/admin/public_html/legenda/apps/kube/core/web.php on line 72

Notice: Undefined property: model::$hits in /home/admin/public_html/legenda/libs/model.php on line 301
```

This is the first time I've seen Kube by the way and it looks awesome! Gonna give it a shot on my next project. Thanks for your work!

**Comment by imperavi** [comment]
Thanks. Fixed
