### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by jmeas** [imperavi/kube#8]
It should take no more than 30secs to [set up](http://bower.io/#defining-a-package)

**Comment by cihadturhan** [comment]
:+1:

**Comment by malishev** [comment]
+1

**Comment by patchee500** [comment]
+1

**Comment by hurrycaner** [comment]
:+1:

**Comment by hurrycaner** [comment]
@imperavi why close this without an answer? Just add it to bower please :(

**Comment by codefuhrer** [comment]
Time to unstar this repo.

**Comment by dmitry-kostin** [comment]
still no changes? :(
