### ISSUE TITLE
Hyperlinks do not work when using Off Canvas

### ISSUE THREAD

**Issue by bgarrant** [imperavi/kube#89]
For some reason hyperlinks are not working when using with offcanvas.  The hyperlinks are unclickable in the browser with the new 6.5.1 version.

```
// Right + Close
<a href="#" data-component="offcanvas" data-target="#offcanvas-right" data-direction="right">Open Right</a>

<div id="offcanvas-right" class="hide">
    <a href="#" class="close"></a>
    <nav>
        <ul>
            <li><a href="http://google.com">google</a></li>
        </ul>
    </nav>
</div>
```

**Comment by bgarrant** [comment]
It appears to be an issue with class="hide"

**Comment by bgarrant** [comment]
Did more testing an issue is definitely when the class="hide" is used with Offcanvas.  Any idea what is preventing hyperlinks from opening?

**Comment by imperavi** [comment]
Fixed.

**Comment by swttt** [comment]
Having the same issue when using font-awesome icons inside the off canvas links.
When removing the `hide` class it works as expected.
