### ISSUE TITLE
Mistake in https://imperavi.com/kube/docs/custom-plugins/

### ISSUE THREAD

**Issue by artem4ik** [imperavi/kube#90]
Instead
    // Plugin
    Kube.Myplugin.create('Myplugin');
    Kube.Myplugin.autoload('Myplugin');

must be
    // Plugin
    Kube.Plugin.create('Myplugin');
    Kube.Plugin.autoload('Myplugin');

**Comment by imperavi** [comment]
Fixed, thanks.
